general {
    hide_cursor = true
    # grace bestaat niet in v0.9.2 config; als je het wil, gebruik de CLI flag --grace
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan to unlock
        present_message = Scanning...
        retry_delay = 250
    }
}

# Zwart op ALLE schermen
background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%H:%M"
    font_size = 96
    color = rgba(255,255,255,0.6)

    position = 0, 0
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1

    size = 400, 80
    position = 0, -120
    halign = center
    valign = center

    # maak de "box" onzichtbaar
    outline_thickness = 0
    outer_color = rgba(0,0,0,0.0)
    inner_color = rgba(0,0,0,0.0)

    # alleen dots
    dots_center = true
    dots_size = 0.35
    dots_spacing = 0.25
    font_color = rgba(255,255,255,0.4)

    fade_on_empty = true

    # geen teksten
    placeholder_text = ""
    fail_text = ""
}
