# Add a blank line between shell prompts
add_newline = false

# Prompt format
format = """
[](black)${custom.nomad}$username$hostname[](bg:bright-black fg:black)$directory[](fg:bright-black bg:cyan)$git_branch$git_status[](fg:cyan bg:none)$character
"""

# Nomad session marker
[custom.nomad]
when = 'test -n "$NOMAD_BIN"'
format = "[◆ ]($style)"
style = "bg:black fg:bright-cyan bold"

# Username module
[username]
style_user = "bg:black fg:cyan"
style_root = "bg:bright-cyan fg:red"
format = "[$user]($style)"
show_always = true

# Hostname module
[hostname]
style = "bg:black fg:bright-cyan"
format = "[@$hostname]($style)"
disabled = false

# Directory module
[directory]
style = "bg:bright-black fg:white"
format = "[ $path ]($style)"
truncation_length = 3

# Git branch module
[git_branch]
style = "bg:cyan fg:black"
format = "[ $branch ]($style)"

# Git status module
[git_status]
style = "bg:cyan fg:black"
format = "[$all_status]($style)"

# Character at the end
[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](blue)"
